version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"  # Map host port 8080 to Traefik's dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
    networks:
      - new_traefik_network

  app:
    build: .
    networks:
      - new_traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`localhost`) && (PathPrefix(`/api`) || Path(`/health`) || Path(`/docs`) || Path(`/openapi.json`))
      - traefik.http.routers.app.entrypoints=http

networks:
  new_traefik_network:
    external: true
